sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t aliwatters/docker-kubernetes-course-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test