sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t aliwatters/docker-kubernetes-course-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true aliwatters/docker-kubernetes-course-frontend npm run test