sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t aliwatters/docker-kubernetes-course-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true aliwatters/docker-kubernetes-course-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-kubernetes-course-frontend"
  env: "DockerKubernetesCourseFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-621861701423"
  bucket_path: "docker-kubernetes-course-frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY